version: '3.9'

services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python pipeline/train.py &&
               python pipeline/evaluate.py"
    volumes:
      - .:/app
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - pipeline
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"